setx BRICKLINK_STORE_CONSUMER_KEY "<API consumer key>"
setx BRICKLINK_STORE_CONSUMER_SECRET "<API consumer secret>"
setx BRICKLINK_STORE_TOKEN "<API token value>"
setx BRICKLINK_STORE_TOKEN_SECRET "<API token secret>"
setx BRICKLINK_USER_USERNAME "<Account username>"
setx BRICKLINK_USER_PASSWORD "<Account password>"
setx BRICKSET_API_KEY "<API key>"
setx BRICKSET_USERNAME "<Account username>"
setx BRICKSET_PASSWORD "<Account password>"
setx BRICKSET_USER_HASH "<User hash>"
setx LEGO_BAP_AGE "18"
setx LEGO_BAP_COUNTRY_CODE "US"
